eureka:
  instance:
    hostname: ${SERVICES_HOST}
  client:
    service-url:
      defaultZone: http://${SERVICES_HOST}:${DISCOVERY_PORT}/eureka

spring:
  cloud:
    config:
      override-system-properties: false

management:
  tracing:
    sampling:
      probability: 1.0