spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME_AUTH}?ssl=false&application_name=auth-service
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: AuthHikariCp

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    #        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        format_sql: true
        default_schema: public
        jdbc:
          batch_size: 20
          fetch_size: 100
          order_inserts: true
          order_updates: true
          generate_statistics: ${HIBERNATE_STATS:false}  # Optional performance monitoring

  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: public
    baseline-version: 0
    validate-on-migrate: true


logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.flywaydb: DEBUG

server:
  port: ${AUTH_PORT}