spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: izak7901
#    url: jdbc:postgresql://localhost:5432/${AUTH_DB}
#    username: ${POSTGRES_USER}
#    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    showSql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_schema: public

  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: public

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
server:
  port: 8090