spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/v1/api/auth/**

        - id: products-service
          uri: lb://DJANGO-PRODUCTS-SERVICE
          #          uri: http://localhost:8012
          predicates:
            - Path=/v1/api/bizhub/**

        - id: orders-service
          uri: lb://DJANGO-ORDERS-SERVICE
          #          uri: http://localhost:8011
          predicates:
            - Path=/v1/api/bizhub-orderline/**

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/v1/api/payment/**

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/v1/api/notification/**

server:
  port: ${GATEWAY_PORT}
