spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**

        - id: products-service
          #uri: lb://DJANGO-PRODUCTS-SERVICE
          uri: http://localhost:8012
          predicates:
            - Path=/api/v1/bizhub/**

        - id: orders-service
          #uri: lb://DJANGO-ORDERS-SERVICE
          uri: http://localhost:8011
          predicates:
            - Path=/api/v1/bizhub-orderline/**

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payment/**

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notification/**

server:
  port: 8222
