spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notification
    username: postgres
    password: izak7901
    driver-class-name: org.postgresql.Driver

  kafka:
    # TODO:signals connection
    bootstrap-servers: 172.25.0.3:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: payment-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"  # allow all packages for deserialization

    listener:
      ack-mode: record

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_schema: public

  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: public

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 8013
