spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: postgres
    password: izak7901
    #    url: jdbc:postgresql://localhost:5432/${AUTH_DB}
    #    username: ${POSTGRES_USER}
    #    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: payment-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: ""

    listener:
      ack-mode: record

  jpa:
    showSql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_schema: public

    flyway:
      enabled: true
      baseline-on-migrate: true
      schemas: public

  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
server:
  port: 8014
