#django:
#  config:
#    import: file:./secrets/secret.yml
#
#  database:
#    name: ${DJANGO_DB}
#    host: ${POSTGRES_HOST}
#    port: ${POSTGRES_PORT}
#    user: ${POSTGRES_USER}
#    password: ${POSTGRES_PASSWORD}
#  kafka:
#    host: ${KAFKA_HOST}
#    port: ${KAFKA_PORT}
##  secret_key: ${DJANGO_SECRET_KEY}

django:
  database:
#    name: ${DJANGO_DB}
    name: bizhub
    host: localhost
    port: 5432
#    user: ${POSTGRES_USER}
    user: postgres
#    password: ${POSTGRES_PASSWORD}
    password: izak7901
  kafka:
    KAFKA_BOOTSTRAP: http://localhost:9092
    port: 9092

#  minio configurations
  minio:
    MINIO_ACCESS_KEY: CFHfnFtYZLWhVbHpIB9r
    MINIO_SECRET_KEY: 1xhS59CFJa4a1tA83l0nzt2U0GHYfPbpEeQr4oms
    MINIO_BUCKET: bizhub
    MINIO_PORT: 9000
    MINIO_ENDPOINT: http://localhost:9000

