"""
Django settings for orders_service project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
ENV_PATH = Path(__file__).resolve().parents[3] / ".env"

print("BASE_DIR:", BASE_DIR)
print("ENV_PATH:", ENV_PATH)

# Load .env file
if ENV_PATH.exists():
    load_dotenv(ENV_PATH)
else:
    print(f"⚠️  .env file not found at: {ENV_PATH}")

# Now read environment variables
JWT_SECRET = os.getenv("JWT_SECRET")
JWT_ALGORITHM = os.getenv("JWT_ALGORITHM", "HS512")

# settings.py

ORDER_CREATED = os.getenv('ORDER_CREATED')
ORDER_UPDATED = os.getenv('ORDER_UPDATED')
ORDER_DELETED = os.getenv('ORDER_DELETED')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Cors handled by the Spring boot gateway
# Also allow here
ALLOWED_HOSTS = ["*"]

# Url not having the tailing slash at the end
APPEND_SLASH = False

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bizhub_orders.apps.BizhubOrdersConfig',
    'django_microservices.common',
    'rest_framework',
    'drf_spectacular',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'orders_service.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'orders_service.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
# CONFIG_SERVER_URL = config('CONFIG_SERVER_URL')
# SERVER_NAME = config('SERVER_NAME_ORDER', default="django-orders_service")
#
# try:
#     response = requests.get(f"{CONFIG_SERVER_URL}/{SERVER_NAME}/default")
#     response.raise_for_status()
#     properties = response.json().get('propertySources', [])
#     config_data = {}
#     for source in properties:
#         config_data.update(source.get('source', {}))
#
#     print("✅ Config data loaded from Spring Config Server:")
#     print(config_data)
#
# except Exception as e:
#     print(f" Warning: Could not load from spring Config Server: {e}")
#     config_data = {}
#
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'HOST': config_data.get('django.database.host'),
#         'PORT': config_data.get('django.database.port'),
#         'NAME': config_data.get('django.database.name'),
#         'USER': config_data.get('django.database.user'),
#         'PASSWORD': config_data.get('django.database.password'),
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': os.getenv("DB_HOST"),
        'PORT': os.getenv("DB_PORT"),
        'NAME': os.getenv("DB_NAME_ORDER"),
        'USER': os.getenv("DB_USER"),
        'PASSWORD': os.getenv("DB_PASSWORD"),
    }
}

PORT = os.getenv("ORDERS_PORT")

KAFKA_BOOTSTRAP_SERVER = os.getenv("KAFKA_IP4_ADDRESS")
SECRET_KEY = os.getenv('ORDER_SERVICE_SECRET_KEY')

# # SECURITY WARNING: keep the secret key used in production secret!
# PORT = config_data.get('django.server.port')
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# jwt_token to verify token from spring boot Auth service
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        'django_microservices.common.auth.internal_service_authentication.InternalServiceAuthentication',
        'django_microservices.common.auth.authentication.JWTAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}
# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SPECTACULAR_SETTINGS = {
    'TITLE': 'ORDERS SERVICE API',
    'DESCRIPTION': 'API documentation',
    'VERSION': '1.0.0',
}
