# Building layer
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app
# Copy pom.xml and download dependencies
COPY pom.xml
RUN mn dependency:go-offline -B
COPY src ./src
RUN mvn clean dependency:go-offline -B
# caching
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

# Install wget for HealthCheck
RUN apk add --no-cache wget

# create a non-root user  for spring boot
RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring

# Copy jar and explode it for execution
COPY --from=build /app/target/*.jar app.jar
# expose port here or in K3s
EXPOSE 8013
# HealthCheck
HEALTHCHECK --interval=30s --timeout=3s --start-period=10 --retries=3 \
  CMD wget --quiet --tries=1 --spider http://localhost:8013/actutor/health || exit 1
ENTRYPOINT ["java", "-jar", "-Xmx256m", "app.jar"]