# Generated by Django 5.1.2 on 2025-10-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizhub_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
