# Building layer
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app
# Copy pom.xml and download dependencies
COPY pom.xml .
RUN mvn dependency:go-offline -B
COPY src ./src
RUN mvn clean dependency:go-offline -B
# Caching
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

# Install wget for healthCheck
RUN apk add --no-cache wget

RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring

# Copy JAR and explode it for layered execution
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8888
# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=10s --retries=3 \
  CMD wget --quiet --tries=1 --spider http://localhost:8888/actuator/health || exit 1

ENTRYPOINT ["java", "-jar", "-Xmx256m", "app.jar"]