apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server # means this app name belongs  to the app name of this kind***
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: localhost:5000/config-server:latest # Remember the building of images local registry
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: spring-server-config
                  key: SERVER_PORT
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: spring-server-config
                  key: SPRING_PROFILES_ACTIVE
          #            - name: SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS
          #              valueFrom:
          #                configMapKeyRef:
          #                  name: spring-server-config
          #                  key: SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS
          resources:
            requests:
              memory: "256Mi" # 256 megabytes
              cpu: "100m" # millicore
            limits:
              memory: "512Mi"
              cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: microservices
spec:
  selector:
    app: config-server
  ports:
    - port: 8888
      targetPort: 8888
