apiVersion: qpps/v1
kind: Deployment
metadata:
  name: products-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-service
  template:
    metadata:
      labels: products-service
  spec:
    containers:
      - name: products-service
        image: localhost:5000/notificaation-service:latest
        imagePullPolicy: always
        env:
          - name: PRODUCTS_PORT
            valueFrom:
              configMapKeyRef:
                name: microservices-config
                key: PRODUCTS_PORT
          - name: KAFKA_IP4_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: microservices-config
                key: KAFKA_IP4_ADDRESS
          # database-config
          - name: DB_HOST
            value: "postgres-service" # TODO: create postgres-service for postgres
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: microservices-config
                key: DB_PORT
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: microservices-config
                key: DB_USER
          - name: DB_NAME_PRODUCT
            valueFrom:
              configMapKeyRef:
                name: microservices-config
                key: DB_NAME_PRODUCT
          # Eureka
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            valueFrom:
              configMapKeyRef:
              name: auth-service-config
              key: EUREKA_SERVER

          # Database password (from secret)
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: DB_PASSWORD

          # MinIO server
          - name: MINIO_ENDPOINT
            value: "minio-service"
          - name: MINIO_PORT
            valueFrom:
              configMapKeyRef:
                name: microservice-config
                key: MINIO_PORT
          - name: MINIO_BUCKET
            valueFrom:
              configMapKeyRef:
                name: microservice-config
                key: MINIO_BUCKET
          # kafka-topics
          # products
          - name: PRODUCT_CREATED
            valueFrom:
              configMapKeyRef:
                name: microservice-config
                key: PRODUCT_CREATED
          - name: PRODUCT_UPDATED
            valueFrom:
              configMapKeyRef:
                name: microservice-config
                key: PRODUCT_UPDATED
          - name: PRODUCT_DELETED
            valueFrom:
              configMapKeyRef:
                name: microservice-config
                key: PRODUCT_DELETED
          # orders
          - name: ORDER_CREATED
            valueFrom:
              configMapKeyRef:
                name: microservice-config
                key: ORDER_CREATED
          - name: ORDER_UPDATED
            valueFrom:
              configMapKeyRef:
                name: microservice-config
                key: ORDER_UPDATED
          - name: ORDER_DELETED
            valueFrom:
              configMapKeyRef:
                name: microservice-config
                key: ORDER_DELETED
          # jwt algorithm
          - name: JWT_ALGORITHM
            valueFrom:
              configMapKeyRef:
                name: microservices-config
                key: JWT_ALGORITHM

        resources:
          requests:
            memory: "256Mi"
            cpu: "100"
          limits:
            memory: "512Mi"
            cpu: "200"

---
apiVersion: v1
kind: Service
metadata:
  name: products-service
  namespace: microservices
spec:
  selector:
    app: products-service
  ports:
    - port: 8012
      targetPort: 8012