# Generated by Django 5.1.2 on 2025-10-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizhub_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcache',
            name='product_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
